from dataclasses import dataclass
from dotenv import load_dotenv
import os

load_dotenv()

def env_bool(name, default=False):
    v = os.getenv(name)
    return default if v is None else v.strip().lower() in {"1","true","yes","on"}

@dataclass
class Settings:
    auto_session_profit_pct: float = float(os.getenv("AUTO_SESSION_PROFIT_PCT", "1.00"))
    auto_session_loss_pct: float = float(os.getenv("AUTO_SESSION_LOSS_PCT", "2.00"))
    min_rr: float = float(os.getenv("MIN_RR", "1.50"))
    ollama_url: str = os.getenv("OLLAMA_URL", "http://127.0.0.1:11434").rstrip("/")
    ollama_model: str = os.getenv("OLLAMA_MODEL", "deepseek-r1:1.5b")
    ollama_timeout: int = int(os.getenv("OLLAMA_TIMEOUT", "180"))
    ollama_num_predict: int = int(os.getenv("OLLAMA_NUM_PREDICT", "180"))
    ollama_retry_num_predict: int = int(os.getenv("OLLAMA_RETRY_NUM_PREDICT", "110"))
    ollama_empty_retry_num_predict: int = int(os.getenv("OLLAMA_EMPTY_RETRY_NUM_PREDICT", "72"))
    ollama_disable_thinking: bool = env_bool("OLLAMA_DISABLE_THINKING", True)
    ollama_force_json_format: bool = env_bool("OLLAMA_FORCE_JSON_FORMAT", True)
    ollama_probe_num_predict: int = int(os.getenv("OLLAMA_PROBE_NUM_PREDICT", "48"))
    ollama_schema_output: bool = env_bool("OLLAMA_SCHEMA_OUTPUT", True)
    ollama_schema_num_predict: int = int(os.getenv("OLLAMA_SCHEMA_NUM_PREDICT", "220"))
    ollama_malformed_cooldown_sec: int = int(os.getenv("OLLAMA_MALFORMED_COOLDOWN_SEC", "10"))
    ollama_empty_cooldown_sec: int = int(os.getenv("OLLAMA_EMPTY_COOLDOWN_SEC", "20"))
    deterministic_fallback_enabled: bool = env_bool("DETERMINISTIC_FALLBACK_ENABLED", True)
    deterministic_fallback_min_tech: float = float(os.getenv("DETERMINISTIC_FALLBACK_MIN_TECH", "0.92"))
    deterministic_fallback_min_tvtech: float = float(os.getenv("DETERMINISTIC_FALLBACK_MIN_TVTECH", "0.30"))
    deterministic_fallback_min_micro: float = float(os.getenv("DETERMINISTIC_FALLBACK_MIN_MICRO", "0.65"))
    deterministic_fallback_confidence: float = float(os.getenv("DETERMINISTIC_FALLBACK_CONFIDENCE", "0.69"))
    deterministic_fallback_min_consensus: float = float(os.getenv("DETERMINISTIC_FALLBACK_MIN_CONSENSUS", "0.28"))
    deterministic_fallback_min_votes: int = int(os.getenv("DETERMINISTIC_FALLBACK_MIN_VOTES", "2"))
    ollama_degraded_empty_threshold: int = int(os.getenv("OLLAMA_DEGRADED_EMPTY_THRESHOLD", "3"))
    ollama_degraded_recovery_sec: int = int(os.getenv("OLLAMA_DEGRADED_RECOVERY_SEC", "60"))
    unsupported_fallback_min_tech: float = float(os.getenv("UNSUPPORTED_FALLBACK_MIN_TECH", "0.95"))
    unsupported_fallback_min_micro: float = float(os.getenv("UNSUPPORTED_FALLBACK_MIN_MICRO", "0.80"))
    unsupported_fallback_min_consensus: float = float(os.getenv("UNSUPPORTED_FALLBACK_MIN_CONSENSUS", "0.34"))
    hold_override_enabled: bool = env_bool("HOLD_OVERRIDE_ENABLED", True)
    hold_override_confidence: float = float(os.getenv("HOLD_OVERRIDE_CONFIDENCE", "0.69"))
    hold_override_m1_min_tech: float = float(os.getenv("HOLD_OVERRIDE_M1_MIN_TECH", "0.95"))
    hold_override_m1_min_tv: float = float(os.getenv("HOLD_OVERRIDE_M1_MIN_TV", "0.30"))
    hold_override_m1_min_micro: float = float(os.getenv("HOLD_OVERRIDE_M1_MIN_MICRO", "0.80"))
    hold_override_m1_min_consensus: float = float(os.getenv("HOLD_OVERRIDE_M1_MIN_CONSENSUS", "0.38"))
    hold_override_other_min_tech: float = float(os.getenv("HOLD_OVERRIDE_OTHER_MIN_TECH", "0.93"))
    hold_override_other_min_tv: float = float(os.getenv("HOLD_OVERRIDE_OTHER_MIN_TV", "0.25"))
    hold_override_other_min_micro: float = float(os.getenv("HOLD_OVERRIDE_OTHER_MIN_MICRO", "0.70"))
    hold_override_other_min_consensus: float = float(os.getenv("HOLD_OVERRIDE_OTHER_MIN_CONSENSUS", "0.34"))
    macro_micro_enabled: bool = env_bool("MACRO_MICRO_ENABLED", True)
    macro_context_file: str = os.getenv("MACRO_CONTEXT_FILE", "data/macro_context.json")
    macro_api_url: str = os.getenv("MACRO_API_URL", "").strip()
    macro_api_key: str = os.getenv("MACRO_API_KEY", "").strip()
    macro_timeout: int = int(os.getenv("MACRO_TIMEOUT", "8"))
    macro_max_age_minutes: int = int(os.getenv("MACRO_MAX_AGE_MINUTES", "180"))
    macro_high_impact_block_minutes: int = int(os.getenv("MACRO_HIGH_IMPACT_BLOCK_MINUTES", "30"))
    macro_score_weight: float = float(os.getenv("MACRO_SCORE_WEIGHT", "0.10"))
    micro_score_weight: float = float(os.getenv("MICRO_SCORE_WEIGHT", "0.08"))
    zpi_enabled: bool = env_bool("ZPI_ENABLED", True)
    zpi_api_key: str = os.getenv("ZPI_API_KEY", "").strip()
    zpi_base_url: str = os.getenv("ZPI_BASE_URL", "https://api.zpi.web.id").rstrip("/")
    zpi_timeout: int = int(os.getenv("ZPI_TIMEOUT", "12"))
    zpi_news_cache_minutes: int = int(os.getenv("ZPI_NEWS_CACHE_MINUTES", "20"))
    zpi_calendar_cache_minutes: int = int(os.getenv("ZPI_CALENDAR_CACHE_MINUTES", "60"))
    zpi_news_count: int = int(os.getenv("ZPI_NEWS_COUNT", "15"))
    zpi_sentiment_weight: float = float(os.getenv("ZPI_SENTIMENT_WEIGHT", "0.10"))
    zpi_technicals_cache_minutes: int = int(os.getenv("ZPI_TECHNICALS_CACHE_MINUTES", "10"))
    zpi_fear_greed_cache_minutes: int = int(os.getenv("ZPI_FEAR_GREED_CACHE_MINUTES", "60"))
    zpi_klines_cache_minutes: int = int(os.getenv("ZPI_KLINES_CACHE_MINUTES", "10"))
    zpi_technical_weight: float = float(os.getenv("ZPI_TECHNICAL_WEIGHT", "0.08"))
    zpi_fear_greed_weight: float = float(os.getenv("ZPI_FEAR_GREED_WEIGHT", "0.05"))

    symbol: str = os.getenv("SYMBOL", "EURUSD")
    timeframe: str = os.getenv("TIMEFRAME", "M15").upper()
    trading_mode: str = os.getenv("TRADING_MODE", "AUTO").upper()
    magic: int = int(os.getenv("MAGIC", "26082202"))

    live_trading: bool = env_bool("LIVE_TRADING", True)
    account_unit_mode: str = os.getenv("ACCOUNT_UNIT_MODE", "STANDARD").strip().upper()

    profit_target: float = float(os.getenv("PROFIT_TARGET", "20.00"))
    max_session_loss: float = float(os.getenv("MAX_SESSION_LOSS", "10.00"))

    max_open_positions: int = max(20, int(os.getenv("MAX_OPEN_POSITIONS", "20")))
    dynamic_risk_min_pct: float = float(os.getenv("DYNAMIC_RISK_MIN_PCT", "0.20"))
    dynamic_risk_max_pct: float = float(os.getenv("DYNAMIC_RISK_MAX_PCT", "0.75"))
    dynamic_rr_min: float = float(os.getenv("DYNAMIC_RR_MIN", "1.30"))
    dynamic_rr_max: float = float(os.getenv("DYNAMIC_RR_MAX", "2.20"))
    adaptive_target_enabled: bool = env_bool("ADAPTIVE_TARGET_ENABLED", True)
    adaptive_min_reward_risk: float = float(os.getenv("ADAPTIVE_MIN_REWARD_RISK", "2.00"))
    adaptive_scalping_floor_pct: float = float(os.getenv("ADAPTIVE_SCALPING_FLOOR_PCT", "2.00"))
    adaptive_intraday_floor_pct: float = float(os.getenv("ADAPTIVE_INTRADAY_FLOOR_PCT", "2.00"))
    adaptive_swing_floor_pct: float = float(os.getenv("ADAPTIVE_SWING_FLOOR_PCT", "2.00"))
    adaptive_scalping_max_target_pct: float = float(os.getenv("ADAPTIVE_SCALPING_MAX_TARGET_PCT", "6.00"))
    adaptive_intraday_max_target_pct: float = float(os.getenv("ADAPTIVE_INTRADAY_MAX_TARGET_PCT", "12.00"))
    adaptive_swing_max_target_pct: float = float(os.getenv("ADAPTIVE_SWING_MAX_TARGET_PCT", "25.00"))
    auto_dynamic_timeframe: bool = env_bool("AUTO_DYNAMIC_TIMEFRAME", True)
    auto_tf_candidates: str = os.getenv("AUTO_TF_CANDIDATES", "M1,M5,M15,M30,H1,H4")
    auto_tf_min_confidence: float = float(os.getenv("AUTO_TF_MIN_CONFIDENCE", "0.58"))
    auto_tf_switch_margin: float = float(os.getenv("AUTO_TF_SWITCH_MARGIN", "0.06"))
    session_intelligence_enabled: bool = env_bool("SESSION_INTELLIGENCE_ENABLED", True)
    session_timezone_offset_hours: float = float(os.getenv("SESSION_TIMEZONE_OFFSET_HOURS", "7"))
    session_tokyo_start: str = os.getenv("SESSION_TOKYO_START", "07:00")
    session_tokyo_end: str = os.getenv("SESSION_TOKYO_END", "14:00")
    session_london_start: str = os.getenv("SESSION_LONDON_START", "14:00")
    session_london_end: str = os.getenv("SESSION_LONDON_END", "20:30")
    session_newyork_start: str = os.getenv("SESSION_NEWYORK_START", "20:30")
    session_newyork_end: str = os.getenv("SESSION_NEWYORK_END", "05:00")
    session_signal_weight: float = float(os.getenv("SESSION_SIGNAL_WEIGHT", "0.05"))

    fibonacci_enabled: bool = env_bool("FIBONACCI_ENABLED", True)
    fibonacci_lookback_bars: int = int(os.getenv("FIBONACCI_LOOKBACK_BARS", "55"))
    fibonacci_near_atr: float = float(os.getenv("FIBONACCI_NEAR_ATR", "0.40"))
    fibonacci_signal_weight: float = float(os.getenv("FIBONACCI_SIGNAL_WEIGHT", "0.06"))
    fibonacci_tp_extension_enabled: bool = env_bool("FIBONACCI_TP_EXTENSION_ENABLED", True)
    dynamic_exit_management_enabled: bool = env_bool("DYNAMIC_EXIT_MANAGEMENT_ENABLED", True)
    dynamic_tp_min_extension_pct: float = float(os.getenv("DYNAMIC_TP_MIN_EXTENSION_PCT", "0.15"))
    profit_lock_trigger_pct: float = float(os.getenv("PROFIT_LOCK_TRIGGER_PCT", "1.00"))
    profit_lock_pct: float = float(os.getenv("PROFIT_LOCK_PCT", "0.20"))
    profit_trail_trigger_pct: float = float(os.getenv("PROFIT_TRAIL_TRIGGER_PCT", "2.00"))
    profit_trail_gap_pct: float = float(os.getenv("PROFIT_TRAIL_GAP_PCT", "1.00"))
    dynamic_session_profit_min_pct: float = float(os.getenv("DYNAMIC_SESSION_PROFIT_MIN_PCT", "0.60"))
    dynamic_session_profit_max_pct: float = float(os.getenv("DYNAMIC_SESSION_PROFIT_MAX_PCT", "1.50"))
    dynamic_session_loss_min_pct: float = float(os.getenv("DYNAMIC_SESSION_LOSS_MIN_PCT", "0.80"))
    dynamic_session_loss_max_pct: float = float(os.getenv("DYNAMIC_SESSION_LOSS_MAX_PCT", "2.00"))
    add_position_min_distance_atr: float = float(os.getenv("ADD_POSITION_MIN_DISTANCE_ATR", "0.35"))
    add_position_min_conf: float = float(os.getenv("ADD_POSITION_MIN_CONF", "0.88"))
    max_total_risk_pct: float = float(os.getenv("MAX_TOTAL_RISK_PCT", "3.0"))
    min_margin_level_pct: float = float(os.getenv("MIN_MARGIN_LEVEL_PCT", "500.0"))
    adaptive_margin_sizing: bool = env_bool("ADAPTIVE_MARGIN_SIZING", True)
    margin_free_buffer_pct: float = float(os.getenv("MARGIN_FREE_BUFFER_PCT", "5.0"))
    margin_volume_search_steps: int = int(os.getenv("MARGIN_VOLUME_SEARCH_STEPS", "20"))
    max_symbol_positions: int = max(10, int(os.getenv("MAX_SYMBOL_POSITIONS", "10")))
    margin_driven_multi_entry: bool = env_bool("MARGIN_DRIVEN_MULTI_ENTRY", True)
    risk_per_trade_pct: float = float(os.getenv("RISK_PER_TRADE_PCT", "0.25"))
    min_confidence: float = float(os.getenv("MIN_CONFIDENCE", "0.68"))
    min_final_score: float = float(os.getenv("MIN_FINAL_SCORE", "0.66"))
    min_rr: float = float(os.getenv("MIN_RR", "1.50"))
    sl_atr_mult: float = float(os.getenv("SL_ATR_MULT", "1.5"))
    tp_atr_mult: float = float(os.getenv("TP_ATR_MULT", "2.25"))
    deviation_points: int = int(os.getenv("DEVIATION_POINTS", "20"))
    max_spread_pct_forex: float = float(os.getenv("MAX_SPREAD_PCT_FOREX", "0.05"))
    max_spread_pct_metals: float = float(os.getenv("MAX_SPREAD_PCT_METALS", "0.15"))
    max_spread_pct_crypto: float = float(os.getenv("MAX_SPREAD_PCT_CRYPTO", "0.30"))
    max_spread_pct_indices: float = float(os.getenv("MAX_SPREAD_PCT_INDICES", "0.15"))
    max_spread_pct_energies: float = float(os.getenv("MAX_SPREAD_PCT_ENERGIES", "0.20"))
    max_spread_pct_stocks: float = float(os.getenv("MAX_SPREAD_PCT_STOCKS", "0.30"))
    max_spread_pct_synthetics: float = float(os.getenv("MAX_SPREAD_PCT_SYNTHETICS", "0.30"))
    max_spread_pct_other: float = float(os.getenv("MAX_SPREAD_PCT_OTHER", "0.20"))

    similar_trades_limit: int = int(os.getenv("SIMILAR_TRADES_LIMIT", "20"))
    min_similar_for_weight: int = int(os.getenv("MIN_SIMILAR_FOR_WEIGHT", "5"))
    cooldown_candles_after_loss: int = int(os.getenv("COOLDOWN_CANDLES_AFTER_LOSS", "1"))
    max_consecutive_losses: int = int(os.getenv("MAX_CONSECUTIVE_LOSSES", "3"))
    pause_candles_after_streak: int = int(os.getenv("PAUSE_CANDLES_AFTER_STREAK", "4"))

    symbol_scan_limit: int = int(os.getenv("SYMBOL_SCAN_LIMIT", "12"))
    llm_memory_limit: int = int(os.getenv("LLM_MEMORY_LIMIT", "6"))
    bars: int = int(os.getenv("BARS", "500"))
